---
# This playbook is to install android SDK updates in all the agents
- name: Android SDK update
  hosts: agents

  tasks:
    - name: Updating all the Android packages
      ansible.builtin.shell: yes | /usr/local/bin/sdkmanager --update --channel=1
