---
# This playbook is to install android SDK updates in all the agents
- hosts: agents

  tasks:
   - name: Updating all the Android packages
     shell: yes | /usr/local/bin/sdkmanager --update --channel=1
