name: Build

on: [push, pull_request]

jobs:

  # -- TESTS ------------------------------------------------------------------
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@b4401455ef773683d2da2e176e3539cce0fabdc7
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@98f605ebfe61d25ccbaaf090d5fc598a14bb35c6 # tag=v6.6.1

  # -- SAST SCAN --------------------------------------------------------------
  code-security:
    runs-on: ubuntu-latest
    needs: tests
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@b4401455ef773683d2da2e176e3539cce0fabdc7
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master

        env:
          WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_ANNOTATE_PR: true

      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3.1.1
        with:
          name: reports
          path: reports

  # -- RELEASE ----------------------------------------------------------------
  release:
    runs-on: ubuntu-latest
    needs: code-security
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@b4401455ef773683d2da2e176e3539cce0fabdc7
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@be27b56c2b7c71f71285b5a52067a40ad8b4c516 # tag=v3.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
