name: Code Review

on: [pull_request]

jobs:

  # -- LINT -------------------------------------------------------------------
  ansible-lint:
    name: runner / ansible-lint
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@f8b229487278099721572481264761b1d4fdd530
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Prepare Ansible Lint
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: 3.6

      - name: Run Ansible Lint
        uses: reviewdog/action-ansiblelint@e4f77a3694e03131cd35df74ad67dc089ca36309 # tag=v1.6.2
