name: Code Review

on: [pull_request]

jobs:

  # -- LINT -------------------------------------------------------------------
  ansible-lint:
    name: runner / ansible-lint
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@8a1ef77ccd7a6d18b009c8cd833b00f49386b657
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Prepare Ansible Lint
        uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912 # v4.4.0
        with:
          python-version: 3.6

      - name: Run Ansible Lint
        uses: reviewdog/action-ansiblelint@e4f77a3694e03131cd35df74ad67dc089ca36309 # tag=v1.6.2
