name: Code Review

on: [pull_request]

jobs:

  # -- LINT -------------------------------------------------------------------
  ansible-lint:
    name: runner / ansible-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3.0.1

      - name: Prepare Ansible Lint
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6 # tag=v3.1.2
        with:
          python-version: 3.6

      - name: Run Ansible Lint
        uses: reviewdog/action-ansiblelint@ecf76687849cdb732377c42726b37cef88ec9f81 # tag=v1.5.1
