name: Code Review

on: [pull_request]

jobs:

  # -- LINT -------------------------------------------------------------------
  ansible-lint:
    name: runner / ansible-lint
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@cdea734fa57747b9831aa9d6fcb274c5f9669557
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Prepare Ansible Lint
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6 # tag=v3.1.2
        with:
          python-version: 3.6

      - name: Run Ansible Lint
        uses: reviewdog/action-ansiblelint@81a7b4fc172d08bd242bfc0138bd98cab97206bb # tag=v1.6.1
