name: reviewdog

on: [pull_request]

jobs:
  ansible-lint:
    name: runner / ansible-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Ansible Lint
        uses: actions/setup-python@7a69c2bc7dc38832443a11bc7c2550ba96c6f45c # tag=v2.0.2
        with:
          python-version: 3.6

      - name: Run Ansible Lint
        uses: reviewdog/action-ansiblelint@bf3f386afa2e3a944e96f1dce58a68b7b6af9d25 # tag=v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
